# Generated by Django 4.1.5 on 2024-12-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rider_number', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(choices=[('National', 'National'), ('Novice', 'Novice')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('National', 'National'), ('Novice', 'Novice')], max_length=8)),
                ('racers', models.ManyToManyField(related_name='groups', to='racers.racer')),
            ],
        ),
        migrations.CreateModel(
            name='SortedLapTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_time', models.CharField(max_length=10)),
                ('rank', models.IntegerField(help_text='Rank of the lap time from fastest to slowest')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorted_laptimes', to='racers.racer')),
            ],
            options={
                'ordering': ['racer', 'rank'],
                'unique_together': {('racer', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='RaceModeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_position', models.CharField(blank=True, max_length=10, null=True)),
                ('penalty', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_mode_data', to='racers.group')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_mode_data', to='racers.racer')),
            ],
            options={
                'unique_together': {('racer', 'finish_position', 'group')},
            },
        ),
        migrations.CreateModel(
            name='LapTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_time', models.CharField(max_length=10)),
                ('lap_number', models.IntegerField()),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='racers.racer')),
            ],
            options={
                'unique_together': {('racer', 'lap_number')},
            },
        ),
    ]
