# Generated by Django 5.0.2 on 2025-04-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='transponder_id',
            field=models.CharField(blank=True, help_text='Assigned transponder ID during qualifying', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('National', 'National'), ('Novice', 'Novice'), ('Nari', 'Nari')], max_length=8),
        ),
        migrations.AlterField(
            model_name='racer',
            name='category',
            field=models.CharField(choices=[('National', 'National'), ('Novice', 'Novice'), ('Nari', 'Nari')], max_length=8),
        ),
        migrations.AlterField(
            model_name='racer',
            name='rider_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='racemodedata',
            unique_together={('racer', 'group')},
        ),
        migrations.AddConstraint(
            model_name='racer',
            constraint=models.UniqueConstraint(fields=('rider_number', 'category'), name='unique_rider_per_category'),
        ),
    ]
