# Generated by Django 5.0.2 on 2025-04-09 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0002_racer_transponder_id_alter_group_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=10)),
                ('heat_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transponder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transponder_id', models.CharField(max_length=20, unique=True)),
                ('is_reserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racers.heat')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racers.racer')),
                ('transponder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racers.transponder')),
            ],
        ),
    ]
