# Generated by Django 5.0.2 on 2024-02-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0002_alter_racemodedata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='racemodedata',
            unique_together={('racer', 'finish_position', 'group')},
        ),
    ]
